apiVersion: v1
kind: Pod
metadata:
  name: fsx-app-4
spec:
  containers:
  - name: app
    image: amazonlinux:2023
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    resources:
      limits:
        #nvidia.com/gpu: 1
        vpc.amazonaws.com/efa: 1
      requests:
        #nvidia.com/gpu: 1
        vpc.amazonaws.com/efa: 1
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: fsx-claim
