apiVersion: v1
kind: Pod
    metadata:
    name: fsx-efa-app-2
    namespace: default
    spec:
    containers:
    - command:
        - tail
        - -f
        image: nvcr.io/nvidia/cuda:12.4.0-devel-ubuntu22.04
        imagePullPolicy: IfNotPresent
        name: app
        resources:
        limits:
            vpc.amazonaws.com/efa: "1"
        requests:
            vpc.amazonaws.com/efa: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
        name: persistent-storage
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: kube-api-access-n249n
        readOnly: true
    volumes:
    - name: persistent-storage
        persistentVolumeClaim:
        claimName: lustre-test