{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    aws:
      service: {{ .Values.externalSecrets.secretStore.provider.aws.service }}
      region: {{ .Values.externalSecrets.secretStore.provider.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.externalSecrets.secretStore.provider.aws.auth.jwt.serviceAccountRef.name }}
            namespace: {{ .Values.externalSecrets.secretStore.provider.aws.auth.jwt.serviceAccountRef.namespace }}
{{- end }}
