apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: inference

resources:
  - namespace.yaml
  - vllm-deployment.yaml

# Uncomment to add multi-GPU deployment
# - vllm-multi-gpu.yaml
